name: learning
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/all.jpg
    - images/chicken.jpg
    - images/dog.jpg
    - images/duck.jpg
    - images/elephant.jpg
    - images/lion.jpg
    - images/pig.jpg
    - images/chicken.mp3
    - images/dog.mp3
    - images/duck.mp3
    - images/elephant.mp3
    - images/lion.mp3
    - images/pig.mp3
